# Generated by Django 5.0.4 on 2024-06-15 07:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('document_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Refinements',
            fields=[
                ('refinement_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Uploader',
            fields=[
                ('uploader_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
        migrations.CreateModel(
            name='DocDetails',
            fields=[
                ('docdetail_id', models.AutoField(primary_key=True, serialize=False)),
                ('docdetail', models.CharField(max_length=255)),
                ('position', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kms_app.documents')),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('term', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('lemma', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['term'], name='kms_app_ter_term_873f61_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostingLists',
            fields=[
                ('postlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('docdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kms_app.docdetails')),
                ('term', models.ForeignKey(db_column='term', on_delete=django.db.models.deletion.CASCADE, to='kms_app.terms')),
            ],
            options={
                'indexes': [models.Index(fields=['term'], name='kms_app_pos_term_a6db9a_idx'), models.Index(fields=['docdetail'], name='kms_app_pos_docdeta_5e44dc_idx')],
            },
        ),
    ]
