# Generated by Django 4.2.9 on 2024-05-25 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocDetails',
            fields=[
                ('docdetail_id', models.AutoField(primary_key=True, serialize=False)),
                ('docdetail', models.CharField(max_length=255)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('document_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Refinements',
            fields=[
                ('refinement_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TermLemmas',
            fields=[
                ('termlemma_id', models.AutoField(primary_key=True, serialize=False)),
                ('termlemma', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('term_id', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PostingLists',
            fields=[
                ('postlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('docdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kms_app.docdetails')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kms_app.terms')),
            ],
        ),
        migrations.CreateModel(
            name='PostingListLemmas',
            fields=[
                ('postlistlemma_id', models.AutoField(primary_key=True, serialize=False)),
                ('docdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kms_app.docdetails')),
                ('termlemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kms_app.termlemmas')),
            ],
        ),
        migrations.AddField(
            model_name='docdetails',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kms_app.documents'),
        ),
    ]
