# Generated by Django 5.0.4 on 2024-06-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='postinglistlemmas',
            index=models.Index(fields=['docdetail'], name='kms_app_pos_docdeta_7f7d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='postinglists',
            index=models.Index(fields=['docdetail'], name='kms_app_pos_docdeta_5e44dc_idx'),
        ),
    ]
